### ISSUE TITLE
Add example how to add users / passwords

### ISSUE THREAD

**Issue by Bouni** [connectitnet/scp-for-docker#1]
Please provide an example how to setup users / passwords and how to manage which directories a user can access.
I want to mount one directory into the container whoch all users can access.

At the moment I get access denied with this `docker-compose.yaml`

```yaml
version: "3.8"

services:
  scp-for-docker:
    container_name: scp-for-docker
    build: ./scp-for-docker
    environment:
      - SCP_USERS=data
      - SCP_data_PWD=password
    ports: 
      - "4422:22"
    restart: always
```

This is what `docker-compose logs -f` shows:

```
scp-for-docker    | chpasswd: password for 'data' changed
scp-for-docker    | Server listening on 0.0.0.0 port 22.
scp-for-docker    | Server listening on :: port 22.
scp-for-docker    | Failed password for data from XX.XXX.XX.X port 9203 ssh2
```
